FROM apache/airflow:3.2.2

USER root

# Java requis pour spark-submit
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow


# Airflow Spark provider + PySpark (includes the spark-submit binaries)
# The transitive dependency `pyspark-client` (used for Spark Connect) has been removed
# because it is not used in this architecture (which relies on the classic SparkSubmitOperator)
# and causes file conflicts with `pyspark`.

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    pyspark==3.5.1 \
    boto3 \
    && pip uninstall -y pyspark-client \
    && pip install --no-cache-dir --force-reinstall --no-deps pyspark==3.5.1