FROM apache/spark:3.5.1

USER root

RUN apt-get update && \
    apt-get install -y \
        wget build-essential libssl-dev zlib1g-dev \
        libncurses5-dev libncursesw5-dev libreadline-dev \
        libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev \
        libexpat1-dev liblzma-dev libffi-dev uuid-dev && \
    wget https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz && \
    tar -xf Python-3.11.9.tgz && \
    cd Python-3.11.9 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && rm -rf Python-3.11.9 Python-3.11.9.tgz && \
    update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 1 && \
    python3.11 -m ensurepip && \
    python3.11 -m pip install --upgrade pip && \
    rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON=python3.11
ENV PYSPARK_DRIVER_PYTHON=python3.11

COPY jars/*.jar /opt/spark/jars/

WORKDIR /opt/spark/project

COPY pyproject.toml ./

RUN python3.11 -m pip install .

USER spark