FROM python:3.11-slim

WORKDIR /usr/app/dbt

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-core==1.12.3 dbt-spark[PyHive]==1.11.0

ENTRYPOINT ["dbt"]